CREATE DATABASE IF NOT EXISTS toko_online CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE toko_online;

CREATE TABLE IF NOT EXISTS products (
  id INT AUTO_INCREMENT PRIMARY KEY,
  id_produk VARCHAR(50) NOT NULL,
  nama_produk VARCHAR(255) NOT NULL,
  tipe_produk VARCHAR(100) NOT NULL,
  deskripsi TEXT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nim VARCHAR(50) NOT NULL,
  nama VARCHAR(255) NOT NULL,
  gender ENUM('pria','wanita') NOT NULL,
  alamat JSON NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

